### ISSUE TITLE
Old FTP helper

### ISSUE THREAD

**Issue by eldeal** [ONSdigital/sdx-downstream-ctp#38]
We have two helpers which each have a 'deliver binary' method in them. I think this is due to moving from FTP to SFTP, so a new helper has been written for SFTP but the old one is still around. Potentially the SDXFTP file can be removed and any methods which are used from it should be moved into the SFTP helper.

**Comment by collisdigital** [comment]
This issue will be closed and a new card created to an FTP library https://trello.com/c/rhcql66x
