### ISSUE TITLE
Queue env var inconsistently named

### ISSUE THREAD

**Issue by eldeal** [ONSdigital/sdx-downstream-ctp#8]
https://github.com/ONSdigital/sdx-downstream-ctp/blob/b9e593c6a2248223111b91e3e3e0d1737b0f86e4/app/settings.py#L29

Env var should be RABBIT_QUEUE to be more consistent with other services, or a more descriptive name - definitely no MQ though.

**Comment by collisdigital** [comment]
Duplicate issue from other repos, not going to be changed.
